name: promptus
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.12.14=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_1
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - onnx=1.17.0=py310he36ed58_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - protobuf=4.25.3=py310h12ddb61_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu121
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.2.3=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - altair==5.5.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==24.3.0
      - blinker==1.9.0
      - cachetools==5.5.0
      - click==8.1.8
      - cuda-python==12.6.2.post1
      - diffusers==0.26.1
      - einops==0.7.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.25.0
      - imhist==0.0.4
      - importlib-metadata==7.2.1
      - invisible-watermark==0.2.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kornia==0.6.9
      - lightning-utilities==0.11.9
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - multidict==6.1.0
      - narwhals==1.19.1
      - numpy==1.26.4
      - nvidia-cuda-runtime-cu12==12.6.77
      - omegaconf==2.3.0
      - onnx-graphsurgeon==0.5.2
      - open-clip-torch==2.24.0
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - packaging==23.2
      - pandas==2.2.3
      - pillow==10.4.0
      - polygraphy==0.49.9
      - propcache==0.2.1
      - pyarrow==18.1.0
      - pydeck==0.9.1
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.0.1
      - pytz==2024.2
      - pywavelets==1.8.0
      - referencing==0.35.1
      - regex==2024.11.6
      - rich==13.9.4
      - rpds-py==0.22.3
      - safetensors==0.4.5
      - scipy==1.12.0
      - sentencepiece==0.2.0
      - six==1.17.0
      - smmap==5.0.1
      - streamlit==1.31.0
      - sympy==1.13.1
      - tenacity==8.5.0
      - tensorrt==10.7.0
      - tensorrt-cu12==10.7.0
      - tensorrt-cu12-bindings==10.7.0
      - tensorrt-cu12-libs==10.7.0
      - timm==1.0.12
      - tokenizers==0.15.2
      - toml==0.10.2
      - torchmetrics==1.3.0.post0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.37.2
      - tzdata==2024.2
      - tzlocal==5.2
      - validators==0.34.0
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /home/wjk/.conda/envs/promptus
